import './globals.css'
import { NextAuthProvider } from './provider'


export const metadata = {
  title: 'Spartan-Video',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
        {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}
